package com.nope.bookshop.ui;

import com.nope.bookshop.dao.BookDAO;
import com.nope.bookshop.dao.CategoryDAO;
import com.nope.bookshop.entity.Author;
import com.nope.bookshop.entity.Book;
import com.nope.bookshop.entity.Category;
import com.nope.bookshop.entity.Keyword;
import com.nope.bookshop.entity.Publisher;
import com.nope.bookshop.entity.Vat;
import com.nope.bookshop.exception.DatabaseException;
import com.nope.bookshop.listener.DatabaseUpdateListener;
import com.nope.bookshop.listener.SelectElementListener;
import com.nope.bookshop.res.Strings;
import com.nope.bookshop.uidefault.GenericJDialog;
import com.nope.bookshop.uidefault.SelectableListJPanel;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author zvr
 */
public class BookEditJPanel extends javax.swing.JPanel implements SelectElementListener<Category>{

    private Book book;
    private Window parent;
    private List<DatabaseUpdateListener> listeners;
    private Vat vat;
    private Publisher publisher;
    private List<Author> authors;
    private List<Category> categories;
    private List<Keyword> keywords;
    private List<Book.BookStatusAssoc> statuses;
    
    
    /**
     * Creates new form AddKeywordJPanel
     * @param parent
     * @param book
     */
    public BookEditJPanel(Window parent, Book book) {
        this.book = book;
        this.parent = parent;
        this.listeners = new ArrayList<>();
        initComponents();
        initFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldsPanel = new javax.swing.JPanel();
        pricePanel = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        isbnSubPanel = new javax.swing.JPanel();
        isbnLabel = new javax.swing.JLabel();
        isbnTextField = new javax.swing.JTextField();
        titleSubPanel = new javax.swing.JPanel();
        titleBookLabel = new javax.swing.JLabel();
        titleBookTextField = new javax.swing.JTextField();
        subtitleSubPanel = new javax.swing.JPanel();
        subtitleLabel = new javax.swing.JLabel();
        subtitleTextField = new javax.swing.JTextField();
        authorPanel = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        editAuthorButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        authorList = new javax.swing.JList<>();
        summaryPanel = new javax.swing.JPanel();
        summaryLabel = new javax.swing.JLabel();
        summaryTextField = new javax.swing.JTextField();
        vatSubPanel = new javax.swing.JPanel();
        vatLabel = new javax.swing.JLabel();
        vatEditButton = new javax.swing.JButton();
        vatTextField = new javax.swing.JTextField();
        publisherSubPanel = new javax.swing.JPanel();
        publisherLabel = new javax.swing.JLabel();
        publisherEditButton = new javax.swing.JButton();
        publisherTextField = new javax.swing.JTextField();
        coverURLSubPanel = new javax.swing.JPanel();
        coverURLLabel = new javax.swing.JLabel();
        coverURLTextField = new javax.swing.JTextField();
        postItSubPanel = new javax.swing.JPanel();
        postItLabel = new javax.swing.JLabel();
        postItTextField = new javax.swing.JTextField();
        shelfSubPanel = new javax.swing.JPanel();
        shelfLabel = new javax.swing.JLabel();
        shelfTextField = new javax.swing.JTextField();
        stockSubPanel = new javax.swing.JPanel();
        stockLabel = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        categoriesSubPanel = new javax.swing.JPanel();
        categoriesLabel = new javax.swing.JLabel();
        categoriesEditButton = new javax.swing.JButton();
        CategoriesTextField = new javax.swing.JTextField();
        keywordsSubPanel = new javax.swing.JPanel();
        keywordsLabel = new javax.swing.JLabel();
        keywordsEditButton = new javax.swing.JButton();
        keywordsTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 600));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Création");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );

        confirmButton.setText("Valider");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        priceLabel.setText("Prix");

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTextField))
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        isbnLabel.setText("ISBN");

        isbnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isbnSubPanelLayout = new javax.swing.GroupLayout(isbnSubPanel);
        isbnSubPanel.setLayout(isbnSubPanelLayout);
        isbnSubPanelLayout.setHorizontalGroup(
            isbnSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isbnSubPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(isbnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbnTextField)
                .addContainerGap())
        );
        isbnSubPanelLayout.setVerticalGroup(
            isbnSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isbnSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isbnSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        titleBookLabel.setText("Titre");

        javax.swing.GroupLayout titleSubPanelLayout = new javax.swing.GroupLayout(titleSubPanel);
        titleSubPanel.setLayout(titleSubPanelLayout);
        titleSubPanelLayout.setHorizontalGroup(
            titleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleBookTextField))
        );
        titleSubPanelLayout.setVerticalGroup(
            titleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleBookLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subtitleLabel.setText("Sous-titre");

        javax.swing.GroupLayout subtitleSubPanelLayout = new javax.swing.GroupLayout(subtitleSubPanel);
        subtitleSubPanel.setLayout(subtitleSubPanelLayout);
        subtitleSubPanelLayout.setHorizontalGroup(
            subtitleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtitleSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleTextField))
        );
        subtitleSubPanelLayout.setVerticalGroup(
            subtitleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtitleSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subtitleSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtitleLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        authorLabel.setText("Auteurs");

        editAuthorButton.setText("Selectionner...");
        editAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAuthorButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(authorList);

        javax.swing.GroupLayout authorPanelLayout = new javax.swing.GroupLayout(authorPanel);
        authorPanel.setLayout(authorPanelLayout);
        authorPanelLayout.setHorizontalGroup(
            authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorPanelLayout.createSequentialGroup()
                .addGroup(authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editAuthorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        authorPanelLayout.setVerticalGroup(
            authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorPanelLayout.createSequentialGroup()
                .addGroup(authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authorPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(authorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAuthorButton))
                    .addGroup(authorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        summaryLabel.setText("Resumé");

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(summaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaryTextField))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summaryLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        vatLabel.setText("TVA");

        vatEditButton.setText("Selectionner...");
        vatEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatEditButtonActionPerformed(evt);
            }
        });

        vatTextField.setEnabled(false);

        javax.swing.GroupLayout vatSubPanelLayout = new javax.swing.GroupLayout(vatSubPanel);
        vatSubPanel.setLayout(vatSubPanelLayout);
        vatSubPanelLayout.setHorizontalGroup(
            vatSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vatSubPanelLayout.createSequentialGroup()
                .addComponent(vatEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(vatSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vatTextField))
        );
        vatSubPanelLayout.setVerticalGroup(
            vatSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vatSubPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(vatSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatLabel)
                    .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vatEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        publisherLabel.setText("Editeur");

        publisherEditButton.setText("Selectionner...");
        publisherEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherEditButtonActionPerformed(evt);
            }
        });

        publisherTextField.setEnabled(false);

        javax.swing.GroupLayout publisherSubPanelLayout = new javax.swing.GroupLayout(publisherSubPanel);
        publisherSubPanel.setLayout(publisherSubPanelLayout);
        publisherSubPanelLayout.setHorizontalGroup(
            publisherSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherSubPanelLayout.createSequentialGroup()
                .addComponent(publisherEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(publisherSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherTextField))
        );
        publisherSubPanelLayout.setVerticalGroup(
            publisherSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publisherSubPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(publisherSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coverURLLabel.setText("Image (URL)");

        javax.swing.GroupLayout coverURLSubPanelLayout = new javax.swing.GroupLayout(coverURLSubPanel);
        coverURLSubPanel.setLayout(coverURLSubPanelLayout);
        coverURLSubPanelLayout.setHorizontalGroup(
            coverURLSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverURLSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverURLTextField))
        );
        coverURLSubPanelLayout.setVerticalGroup(
            coverURLSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverURLSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coverURLSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coverURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coverURLLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        postItLabel.setText("Post-it");

        javax.swing.GroupLayout postItSubPanelLayout = new javax.swing.GroupLayout(postItSubPanel);
        postItSubPanel.setLayout(postItSubPanelLayout);
        postItSubPanelLayout.setHorizontalGroup(
            postItSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postItSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(postItLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postItTextField))
        );
        postItSubPanelLayout.setVerticalGroup(
            postItSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postItSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(postItSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postItTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postItLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shelfLabel.setText("Emplacement");

        javax.swing.GroupLayout shelfSubPanelLayout = new javax.swing.GroupLayout(shelfSubPanel);
        shelfSubPanel.setLayout(shelfSubPanelLayout);
        shelfSubPanelLayout.setHorizontalGroup(
            shelfSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shelfSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shelfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shelfTextField))
        );
        shelfSubPanelLayout.setVerticalGroup(
            shelfSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shelfSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shelfSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shelfLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stockLabel.setText("Quantité stock");

        javax.swing.GroupLayout stockSubPanelLayout = new javax.swing.GroupLayout(stockSubPanel);
        stockSubPanel.setLayout(stockSubPanelLayout);
        stockSubPanelLayout.setHorizontalGroup(
            stockSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockTextField))
        );
        stockSubPanelLayout.setVerticalGroup(
            stockSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stockSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoriesLabel.setText("Categories");

        categoriesEditButton.setText("Selectionner...");
        categoriesEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesEditButtonActionPerformed(evt);
            }
        });

        CategoriesTextField.setEnabled(false);

        javax.swing.GroupLayout categoriesSubPanelLayout = new javax.swing.GroupLayout(categoriesSubPanel);
        categoriesSubPanel.setLayout(categoriesSubPanelLayout);
        categoriesSubPanelLayout.setHorizontalGroup(
            categoriesSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesSubPanelLayout.createSequentialGroup()
                .addComponent(categoriesEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(categoriesSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriesTextField))
        );
        categoriesSubPanelLayout.setVerticalGroup(
            categoriesSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesSubPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(categoriesSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesLabel)
                    .addComponent(CategoriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriesEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        keywordsLabel.setText("Mot-clefs");

        keywordsEditButton.setText("Selectionner...");
        keywordsEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordsEditButtonActionPerformed(evt);
            }
        });

        keywordsTextField.setEnabled(false);

        javax.swing.GroupLayout keywordsSubPanelLayout = new javax.swing.GroupLayout(keywordsSubPanel);
        keywordsSubPanel.setLayout(keywordsSubPanelLayout);
        keywordsSubPanelLayout.setHorizontalGroup(
            keywordsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keywordsSubPanelLayout.createSequentialGroup()
                .addComponent(keywordsEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(keywordsSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keywordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keywordsTextField))
        );
        keywordsSubPanelLayout.setVerticalGroup(
            keywordsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keywordsSubPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(keywordsSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordsLabel)
                    .addComponent(keywordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keywordsEditButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isbnSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtitleSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pricePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vatSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(publisherSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coverURLSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postItSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shelfSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriesSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keywordsSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addComponent(isbnSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vatSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publisherSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coverURLSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postItSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shelfSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoriesSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keywordsSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(fieldsPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isbnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        confirmAction();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteAction();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void categoriesEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesEditButtonActionPerformed
        editCategoriesAction();
    }//GEN-LAST:event_categoriesEditButtonActionPerformed

    private void keywordsEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordsEditButtonActionPerformed
        editKeywordAction();
    }//GEN-LAST:event_keywordsEditButtonActionPerformed

    private void editAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAuthorButtonActionPerformed
        editAuthorsAction();
    }//GEN-LAST:event_editAuthorButtonActionPerformed

    private void vatEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatEditButtonActionPerformed
        editVATAction();
    }//GEN-LAST:event_vatEditButtonActionPerformed

    private void publisherEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherEditButtonActionPerformed
        editPublisherAction();
    }//GEN-LAST:event_publisherEditButtonActionPerformed

    protected void initFields(){
        if(book == null){
            return;
        }
        
        isbnTextField.setText(book.getIsbn());
        titleBookTextField.setText(book.getTitle());
        subtitleTextField.setText(book.getSubTitle());
        summaryTextField.setText(book.getSummary());
        priceTextField.setText(""+book.getPrice());
        coverURLTextField.setText(book.getCoverURL());
        postItTextField.setText(book.getPostIt());
        shelfTextField.setText(book.getShelf());
        stockTextField.setText(""+book.getQuantity());
        
    }
    
    protected void cancelAction(){
        int result = JOptionPane.showConfirmDialog(
                this,
                Strings.MSG_ASK_CONFIRMATION,
                Strings.MSG_CANCEL_EDITION,
                JOptionPane.YES_NO_OPTION
        );
        if (parent == null) {
            return;
        }
        if (result == JOptionPane.YES_OPTION) {
            parent.dispose();

        }
    }
    protected void confirmAction(){
        int result = JOptionPane.showConfirmDialog(
                this,
                Strings.MSG_ASK_CONFIRMATION, 
                Strings.MSG_CONFIRM_EDITION, 
                JOptionPane.YES_NO_OPTION
        );
        if(parent == null){
            return;
        }
        if(result == JOptionPane.YES_OPTION){
            book.setIsbn(getISBN());
            book.setTitle(getTitle());
            book.setSubTitle(getSubTitle());
            book.setCoverURL(getCoverURL());
            book.setPostIt(getPostItText());
            book.setShelf(getShelf());
            book.setQuantity(getStock());
            book.setPublisher(getPublisher());
            book.setAuthors(getAuthors());
            book.setCategories(getCategories());
            book.setKeywords(getKeywords());
            book.setStatuses(getStatuses());
            book.setVat(getVat());
            book.setPrice(getPrice());
            
            try {
                new BookDAO().update(book);
            } catch (DatabaseException ex) {
                JOptionPane.showMessageDialog(
                        this, 
                        ex.getMessage(), 
                        Strings.MSG_ERROR, 
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            
            JOptionPane.showMessageDialog(
                    this,
                    Strings.ELEMENT_BOOK + " " + Strings.MSG_SUCCESSFULLY_EDITED,
                    Strings.MSG_INFO,
                    JOptionPane.INFORMATION_MESSAGE
            );

            notifyDatabaseListener();
            parent.dispose();
        }
    }
    protected void deleteAction(){
        int result = JOptionPane.showConfirmDialog(
                this,
                Strings.MSG_ASK_CONFIRMATION,
                Strings.MSG_CONFIRM_DELETION,
                JOptionPane.YES_NO_OPTION
        );
        if (getParentWindow() == null) {
            return;
        }
        if (result == JOptionPane.YES_OPTION) {
            
            try {
                new BookDAO().delete(book);
            } catch (DatabaseException ex) {
                JOptionPane.showMessageDialog(
                        this, 
                        ex.getMessage(), 
                        Strings.MSG_ERROR,
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            JOptionPane.showMessageDialog(
                        this, 
                        Strings.ELEMENT_BOOK+" "+Strings.MSG_SUCCESSFULLY_DELETED, 
                        Strings.MSG_INFO, 
                        JOptionPane.INFORMATION_MESSAGE
            );
            notifyDatabaseListener();
            getParentWindow().dispose();
        }
    }
    
    protected void editPublisherAction(){
        JOptionPane.showMessageDialog(
                this,
                Strings.MSG_WIP_FEATURE,
                Strings.MSG_INFO,
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    protected void editAuthorsAction(){
        JOptionPane.showMessageDialog(
                this,
                Strings.MSG_WIP_FEATURE,
                Strings.MSG_INFO,
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    protected void editKeywordAction(){
        JOptionPane.showMessageDialog(
                this,
                Strings.MSG_WIP_FEATURE,
                Strings.MSG_INFO,
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    protected void editVATAction(){
        JOptionPane.showMessageDialog(
                this,
                Strings.MSG_WIP_FEATURE,
                Strings.MSG_INFO,
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    protected void editCategoriesAction(){
        
        
        GenericJDialog dialog = new GenericJDialog(SwingUtilities.getWindowAncestor(this));
        List<Category> categories = new CategoryDAO().getAll();
        SelectableListJPanel<Category> selectablePanel = new SelectableListJPanel<>(dialog, categories, book.getCategories());
        
        selectablePanel.addListener(this);
        
        dialog.setContentPane(selectablePanel);
        dialog.pack();
        dialog.setLocationRelativeTo(getParentWindow());
        dialog.setVisible(true);
        
    }

    public void addDatabaseListener(DatabaseUpdateListener listener){
        listeners.add(listener);
    }
    
    /**
     * Notify all listeners
     */
    protected void notifyDatabaseListener(){
        for(DatabaseUpdateListener listener : listeners){
            listener.databaseUpdated();
        }
    }
    
    public Window getParentWindow(){
        return parent;
    }
    
    public Book getBook(){
        return book;
    }
    
    public Vat getVat() {
        return vat;
    }

    public Publisher getPublisher() {
        return publisher;
    }

    public List<Author> getAuthors() {
        return authors;
    }

    public List<Category> getCategories() {
        return categories;
    }

    public List<Keyword> getKeywords() {
        return keywords;
    }

    public List<Book.BookStatusAssoc> getStatuses() {
        return statuses;
    }
    
    public String getISBN(){
        return isbnTextField.getText();
    }
    public String getTitle(){
        return titleBookTextField.getText();
    }
    public String getSubTitle(){
        return subtitleTextField.getText();
    }
    public String getSummary(){
        return summaryTextField.getText();
    }
    public float getPrice(){
        return Float.parseFloat(priceTextField.getText());
    }
    public String getCoverURL(){
        return coverURLTextField.getText();
    }
    public String getShelf(){
        return shelfTextField.getText();
    }
    public int getStock() {
        return Integer.parseInt(stockTextField.getText());
    }
    public String getPostItText(){
        return titleBookTextField.getText();
    }

    public void setTitle(String title){
        titleLabel.setText(title);
    }
    
    public void setCancelButton(JButton button){
        cancelButton = button;
    }
    
    /**
     * Whether the delete button is displayed or not
     * 
     * @param isAllowed 
     */
    public void allowDeletion(boolean isAllowed){
        deleteButton.setEnabled(isAllowed);
        deleteButton.setVisible(isAllowed);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoriesTextField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JList<String> authorList;
    private javax.swing.JPanel authorPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton categoriesEditButton;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JPanel categoriesSubPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel coverURLLabel;
    private javax.swing.JPanel coverURLSubPanel;
    private javax.swing.JTextField coverURLTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editAuthorButton;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JPanel isbnSubPanel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keywordsEditButton;
    private javax.swing.JLabel keywordsLabel;
    private javax.swing.JPanel keywordsSubPanel;
    private javax.swing.JTextField keywordsTextField;
    private javax.swing.JLabel postItLabel;
    private javax.swing.JPanel postItSubPanel;
    private javax.swing.JTextField postItTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton publisherEditButton;
    private javax.swing.JButton publisherEditButton1;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JLabel publisherLabel1;
    private javax.swing.JPanel publisherSubPanel;
    private javax.swing.JPanel publisherSubPanel1;
    private javax.swing.JTextField publisherTextField;
    private javax.swing.JTextField publisherTextField1;
    private javax.swing.JLabel shelfLabel;
    private javax.swing.JPanel shelfSubPanel;
    private javax.swing.JTextField shelfTextField;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel stockSubPanel;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JPanel subtitleSubPanel;
    private javax.swing.JTextField subtitleTextField;
    private javax.swing.JLabel summaryLabel;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTextField summaryTextField;
    private javax.swing.JLabel titleBookLabel;
    private javax.swing.JTextField titleBookTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titleSubPanel;
    private javax.swing.JButton vatEditButton;
    private javax.swing.JLabel vatLabel;
    private javax.swing.JPanel vatSubPanel;
    private javax.swing.JTextField vatTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void elementsSelected(List<Category> selectedElements) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
