package swingLib;


import bookshop.PackageStatusF;
import com.nope.bookshop.ui.CategoryListJPanel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import librairie.Order;

import static swingLib.authorJPanel.rs;
import static swingLib.authorJPanel.stmt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import librairie.Author;
	
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cda611
 */
public class PrimoJif extends javax.swing.JInternalFrame {

    private String url = "jdbc:sqlserver://localhost:1433;databaseName=BookShop;"; 
    private String username = "sa"; 
    private String password = "sa"; 
    private Statement stmt;
    private ResultSet rs;
    private Connection connection;
    private ArrayList <Order> orderL;
     private ArrayList <Order> orderTwoL;
    final private  String [] titre = new String [] {"ID Commande", "ID Client ", "Date Commande", "Commentaire"};
    /**
     * Creates new form primoJif
     */
    public PrimoJif() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        schLbl = new javax.swing.JLabel();
        nmClLbl = new javax.swing.JLabel();
        nmLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        schCmdeLbl = new javax.swing.JLabel();
        idCmdeLbl = new javax.swing.JLabel();
        datCmdeLbl = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        schfourniLbl = new javax.swing.JLabel();
        idFourLbl = new javax.swing.JLabel();
        schNmFoLbl = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        schEvLbl = new javax.swing.JLabel();
        nmEvtLbl = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        schFlowBtb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ccelBtb = new CancelButton();
        
        //Initialisation menu
        
        jMenuBar1 = new javax.swing.JMenuBar();
        creaMenu = new javax.swing.JMenu();
        searchMenu = new javax.swing.JMenu();
        commaMenu = new javax.swing.JMenu();
       
        
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Gestionnaire de commande");

        jTable1.setModel(getDefaultTableModel());
//new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            titre
      
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(getDefaultTwoTableModel()
        );
        jScrollPane2.setViewportView(jTable2);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        schLbl.setText("Recherche client");

        nmClLbl.setText("ID Client");

        nmLbl.setText("Nom");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        schCmdeLbl.setText("Recherche commande");

        idCmdeLbl.setText("NÂ° ");

        datCmdeLbl.setText("Date Cmde");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        schfourniLbl.setText("Recherche fournisseur");

        idFourLbl.setText("nÂ° ID");

        schNmFoLbl.setText("Nom");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        schEvLbl.setText("Recherche par evenement");

        nmEvtLbl.setText("Nom");

        jTextField7.setText("jTextField7");

        schFlowBtb.setBackground(new java.awt.Color(0, 153, 255));
        schFlowBtb.setText("Lancer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(schLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(nmClLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(schCmdeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idCmdeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(datCmdeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(idFourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(schNmFoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nmEvtLbl)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schfourniLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schEvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(schFlowBtb)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(schLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmClLbl)
                    .addComponent(nmLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(schCmdeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCmdeLbl)
                    .addComponent(datCmdeLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(schfourniLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFourLbl)
                    .addComponent(schNmFoLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(schEvLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nmEvtLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(schFlowBtb)
                .addContainerGap())
        );

        jButton1.setText("Suivant");

        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ccelBtb)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ccelBtb))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        
     

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
 
        //Création menu
        creaMenu.setText("Création");
       creaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanel1.setLayout(jPanel1Layout);
                jPanel1.doLayout();
                 jPanel2.setLayout(jPanel2Layout);
                  jPanel1.doLayout();
                jPanel1.validate();
               jPanel2.validate();
                jPanel1.repaint();
                 jPanel2.repaint();
                
                 getContentPane().setLayout(layout);
                  getContentPane().doLayout();
                   jPanel1.revalidate();
                 jPanel2. revalidate();
                 getContentPane().revalidate();
                
            }
            });
        autMenu = new javax.swing.JMenuItem();
        autMenu.setText("Autre...");
        autMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	creaJPanel c1 = new creaJPanel(); 
            	fenetreLib f1 = new fenetreLib(); 
            	f1.getContentPane().add(c1); 
            	f1.setVisible(true);
            	f1.setBounds(c1.getBounds());
                 
                jPanel1.repaint();
                 jPanel2.repaint();
                 jPanel1.revalidate();
                 jPanel2. revalidate();
               
            }
        });
        
        cl1Menu = new javax.swing.JMenuItem();
        cl1Menu.setText("Client");
        cl1Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              clientJPanel cp = new clientJPanel(); 
              fenetreLib fb = new fenetreLib();
              fb.getContentPane().add(cp); 
            }
        });
        
        aut1Menu = new javax.swing.JMenuItem(); 
        aut1Menu.setText("Auteur");
        aut1Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	authorCra a1 = new authorCra();
            	fenetreLib f1 = new fenetreLib(); 
            	f1.getContentPane().add(a1); 
            	f1.setVisible(true);
            	f1.setBounds(a1.getBounds());
                getContentPane().validate();
                 
                
                  
            }
        });
        
        liv1Menu = new javax.swing.JMenuItem();
        liv1Menu.setText("Ouvrage");
        liv1Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                createFramePackageStatus();
            }
        });
        
        eventMenu = new javax.swing.JMenuItem();
        eventMenu.setText("Evenement");
        eventMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               EventCrea e1 = new EventCrea();
               e1.setVisible(true);
            }
            
        });
        
        
      
        catMenu = new javax.swing.JMenuItem();
        catMenu.setText("Catégorie");
        catMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        
        creaMenu.add(cl1Menu);
        creaMenu.add(eventMenu);
        creaMenu.add(catMenu);
        creaMenu.add(aut1Menu);
        creaMenu.add(liv1Menu);
        creaMenu.add(autMenu);

        jMenuBar1.add(creaMenu);

        modifMenu = new javax.swing.JMenu();
        modifMenu.setText("Modification");
       
        clmoMenu = new javax.swing.JMenuItem();
        clmoMenu.setText("Client");
        clmoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        
        autMoMenu = new javax.swing.JMenuItem();
        autMoMenu.setText("Auteur");
        autMoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        
          
        
        livMoMenu = new javax.swing.JMenuItem();
        livMoMenu.setText("Ouvrage");
        livMoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        
        
        prixMoMenu = new javax.swing.JMenuItem();
        prixMoMenu.setText("Prix");
        prixMoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        
        autrMoMenu = new javax.swing.JMenuItem();
        autrMoMenu.setText("Autre...");
        autrMoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        
       
        
        modifMenu.add(clmoMenu); 
        modifMenu.add(autMoMenu);
        modifMenu.add(livMoMenu);
        modifMenu.add(prixMoMenu);
        modifMenu.add(autrMoMenu);

        jMenuBar1.add(modifMenu);

        searchMenu.setText("Recherche");
        
        
        cl1SMenu = new javax.swing.JMenuItem();
        cl1SMenu.setText("Client");
        cl1SMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        
        
        
        
        aut1SMenu = new javax.swing.JMenuItem();
        aut1SMenu.setText("Auteur");
        aut1SMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               try {
				authorJPanel ap = new authorJPanel();
				 fenetreLib f1 = new fenetreLib(); 
				 f1.add(ap); 
				 
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
              
               
            }
        });
        
        livSMenu = new javax.swing.JMenuItem();
        livSMenu.setText("Livre");
        livSMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        
        eventSMenu = new javax.swing.JMenuItem();
        eventSMenu.setText("Evenement");
        eventSMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	EventSearch e1;
				try {
					e1 = new EventSearch();
					fenetreLib f1 = new fenetreLib(); 
	        		f1.add(e1); 
	                
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} 
        		
            }
        });
        
        catSMenu = new javax.swing.JMenuItem();
        catSMenu.setText("Catégorie");
        catSMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFrameCategoryList();
            }
        });
        
        autSMenu = new javax.swing.JMenuItem();
        autSMenu.setText("Autre..."); 
        autSMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	searchJPanel s1 = new searchJPanel(); 
            	fenetreLib f1 = new fenetreLib(); 
            	f1.getContentPane().add(s1); 
               
            }
        });
       
        
        searchMenu.add(cl1SMenu);
        searchMenu.add(aut1SMenu); 
        searchMenu.add(livSMenu); 
        searchMenu.add(eventSMenu); 
        searchMenu.add(catSMenu); 
        searchMenu.add(autSMenu); 
        
        jMenuBar1.add(searchMenu);

        commaMenu.setText("Gestion commande");
        
        gestMenu = new javax.swing.JMenuItem();
        gestMenu.setText("Gestionnaire de commande");
        gestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	orderManager s1;
				try {
					s1 = new orderManager();
					fenetreLib f1 = new fenetreLib(); 
	            	f1.getContentPane().add(s1); 
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} 
            
               
            }
        });
        commaMenu.add(gestMenu);
        jMenuBar1.add(commaMenu);

        setJMenuBar(jMenuBar1);
       
   
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void createFrameCategoryList(){
        
        // Creation d'un JDialog qui va contenir le Panel
        fenetreLib dialog = new fenetreLib();

        // Creation du JPanel permettant l'affichage de la liste des mot-clefs
        CategoryListJPanel categoryListJPanel = new CategoryListJPanel();

        // Definition d'un titre pour le panel d'affichage de la liste des mot-clefs
        //categoryListJPanel.setTitle("titre");

        // Ajout du Panel dans le JDialog
        dialog.setContentPane(categoryListJPanel);

        // Configuration supplementaire et affichage du JDialog 
        dialog.pack();
        dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
       
    }

    
    public void createFramePackageStatus(){
        
        fenetreLib dialog = new fenetreLib();
        
        PackageStatusF frame = new PackageStatusF();
        dialog.setContentPane(frame.getContentPane());

        // Configuration supplementaire et affichage du JDialog 
        dialog.pack();
        dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
        
    }
    
    public DefaultTableModel getDefaultTableModel() throws SQLException{
        Vector<Vector> data = new Vector<>();
        Vector<String> t = new Vector<>();
        t.add("ID Commande"); 
        t.add("ID Client ");
        t.add("Date Commande");
        t.add("Commentaire");
        
       orderL = getOrder();
        for(Order order : orderL){
        
        Vector<Object> row = new Vector<>();
        row.add(order.getId());
        row.add(order.getCustomerId());
        row.add(order.getDateOrder());
        row.add(order.getCommentaire());
        data.add(row);
    }
        
        return new DefaultTableModel(data,t );
    }
    public DefaultTableModel getDefaultTwoTableModel() throws SQLException{
        Vector<Vector> data = new Vector<>();
        Vector<String> t = new Vector<>();
        t.add("ID Commande"); 
        t.add("ID Client ");
        t.add("Date Commande");
        t.add("Commentaire");
        t.add("Statut");
        
       orderTwoL = getTwoOrder();
        for(Order order : orderTwoL){
        
        Vector<Object> row = new Vector<>();
        row.add(order.getId());
        row.add(order.getCustomerId());
        row.add(order.getDateOrder());
        row.add(order.getCommentaire());
        row.add(order.getOrderStatus());
        data.add(row);
    }
        
        return new DefaultTableModel(data,t );
    }
    public ArrayList getOrder() throws SQLException{
     String sql = "Select top 5 * from [Order] ORDER BY [ORDER_CREATION_DATE]";
     orderL = new ArrayList();
     try {
	connection = DriverManager.getConnection(url, username, password);
	stmt = connection.createStatement();
	rs = stmt.executeQuery( sql );
        } catch (SQLException e1) {
	// TODO Auto-generated catch block
	e1.printStackTrace();
}
     
        while (rs.next()){
          
   orderL.add(new Order(rs.getLong("ORDER_ID"), rs.getLong("CUSTOMER_ID"), rs.getString("ORDER_CREATION_DATE"), rs.getString("ORDER_COMMENT")));

}

     

return orderL;
    }
 
    public ArrayList getTwoOrder() throws SQLException{
     String sql = "select [dbo].[ORDER].*, [dbo].[ORDER_STATUS].ORDER_STATUS_NAME  from [dbo].[ORDER] inner join [dbo].[ASSOC_STATUS_ORDER] ON [dbo].[ORDER].ORDER_ID= [dbo].[ASSOC_STATUS_ORDER].ORDER_ID INNER JOIN [dbo].[ORDER_STATUS] ON [dbo].[ASSOC_STATUS_ORDER].ORDER_STATUS_ID=[dbo].[ORDER_STATUS].ORDER_STATUS_ID where ORDER_STATUS_NAME='en cours'" ;
     orderTwoL = new ArrayList();
     try {
	connection = DriverManager.getConnection(url, username, password);
	stmt = connection.createStatement();
	rs = stmt.executeQuery( sql );
        } catch (SQLException e1) {
	// TODO Auto-generated catch block
	e1.printStackTrace();
}
     
        while (rs.next()){
          
   orderTwoL.add(new Order(rs.getLong("ORDER_ID"), rs.getLong("CUSTOMER_ID"), rs.getString("ORDER_CREATION_DATE"), rs.getString("ORDER_COMMENT"), rs.getString("ORDER_STATUS_NAME") ));

}

     

return orderTwoL;
    }
   
public static void main(String [] args) throws SQLException {
	fenetreLib f1 = new fenetreLib(); 
       
	JDesktopPane dp = new JDesktopPane(); 
	PrimoJif p1 = new PrimoJif(); 
    f1.getContentPane().getSize();
	p1.setVisible(true);
	dp.add(p1); 
	dp.setVisible(true);
	f1.add(dp); 
	 f1.setSize(850, 644); 
	f1.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenu creaMenu;
	 
    private javax.swing.JMenuItem aut1Menu;
    private javax.swing.JMenuItem autMoMenu;
    private javax.swing.JMenuItem cl1Menu;
    private javax.swing.JMenuItem clmoMenu;
    private javax.swing.JMenuItem eventMenu;
    private javax.swing.JMenuItem catMenu;
    private javax.swing.JMenuItem autMenu;
    private javax.swing.JMenuItem autrMoMenu;
    
    private javax.swing.JMenuItem cl1SMenu;
    private javax.swing.JMenuItem eventSMenu;
    private javax.swing.JMenuItem catSMenu;
    private javax.swing.JMenuItem autSMenu;
    private javax.swing.JMenuItem aut1SMenu;
    private javax.swing.JMenuItem livSMenu;
    
   
    private javax.swing.JMenuItem liv1Menu;
    private javax.swing.JMenuItem livMoMenu;
    private javax.swing.JMenuItem prixMoMenu;
    
    
    private javax.swing.JMenu searchMenu;
    
    private javax.swing.JMenu modifMenu;
    
    
    private javax.swing.JMenu commaMenu;
    private javax.swing.JMenuItem gestMenu;
    
    private javax.swing.JLabel datCmdeLbl;
    private javax.swing.JLabel idCmdeLbl;
    private javax.swing.JLabel idFourLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;

    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
 
    private javax.swing.JLabel nmClLbl;
    private javax.swing.JLabel nmEvtLbl;
    private javax.swing.JLabel nmLbl;
    private javax.swing.JLabel schCmdeLbl;
    private javax.swing.JLabel schEvLbl;
    private javax.swing.JLabel schLbl;
    private javax.swing.JLabel schNmFoLbl;
    private javax.swing.JLabel schfourniLbl;
    
    private javax.swing.JButton schFlowBtb;
    private CancelButton ccelBtb;
    // End of variables declaration//GEN-END:variables

}
