/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nope.bookshop.visual;

import com.nope.bookshop.dao.EmployeeDAO;
import com.nope.bookshop.entity.Employee;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.nope.bookshop.dao.*;
import com.nope.bookshop.exception.DatabaseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;


/**
 *
 * @author Cy
 */
public class EmployeeJFrame extends javax.swing.JFrame {
    
/**
 * EMPLOYEE TABLE POPULATE CODE: 
 */    
   
    public DefaultTableModel table() throws DatabaseException {
       
            Vector<Vector> vectData = new Vector();
            Vector<String> vectTitle = new Vector();
            
            vectTitle.add("ID");
            vectTitle.add("LOGIN");
            vectTitle.add("PASSWORD");
            vectTitle.add("DATE START");
            vectTitle.add("DATE END");
            
            
            EmployeeDAO employeeDAO = new EmployeeDAO();
            List<Employee> vectList = new ArrayList<>();
             vectList = employeeDAO.getAll();     
            
            for (int i = 0; i < vectList.size(); i++) {
                Employee employee = vectList.get(i);
                System.out.println(employee.getEmployeeId());
                
                Vector vectTable = new Vector();
                vectTable.add(employee.getEmployeeId());
                vectTable.add(employee.getEmployeeLogin());
                vectTable.add(employee.getEmployeePassword());
                vectTable.add(employee.getEmployeeDateStart());
                vectTable.add(employee.getEmployeeDateEnd());
                vectData.add(vectTable);
            }
            
           DefaultTableModel defaultTableModel = new DefaultTableModel(vectData, vectTitle);
            return defaultTableModel;
        }
    
    /**
     * Creates new form EmployeeJFrame
     */
    
    public EmployeeJFrame() {
        initComponents();
        //table();
        // Code to show on center of screen:
        setLocationRelativeTo(null);
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmployee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Employee");
        setMinimumSize(new java.awt.Dimension(800, 600));

        try{
            TableEmployee.setModel(table());
        }catch(DatabaseException e){e.getMessage();}
        TableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableEmployee);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestion Employees");

        jButton1.setText("Sauvegarder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addGap(306, 306, 306)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       /**
        * Quit Button:
        */
        
        
        int quit = JOptionPane.showConfirmDialog(this, "Vous desirez sauvegarder avant quitter?", "Sauvegarder avant quitter?", WIDTH, HEIGHT);
        System.out.println(quit);
        if (quit < 1){
            // answer is YES, SAVE and quit:
            System.out.println("User Terminated application" + " +Save");
            System.out.println("Saving....");
            System.exit(0);
        } else if (quit < 2) {
            // answer is NO, do this:
            System.out.println("User Terminated application" + " +noSave");
            System.exit(0);
        } else {
            // answer is cancel, do this:
            System.out.println("User Tried Terminated application" + " +ExitCanceled");
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
        * Save Button:
        */
        
        System.out.println("User clicked Save button");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEmployeeMouseClicked
        // to select clicked row:
        //TableEmployee.getSelectedRow();
        
    }//GEN-LAST:event_TableEmployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEmployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
